apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kamu-api-server.fullname" . }}-{{ template "kamu-api-server.config.sha" . }}
  labels:
    {{- include "kamu-api-server.labels" . | nindent 4 }}
data:
  {{- include "kamu-api-server.config.yaml" . | nindent 2 }}
  fetch-db-secret.sh: : |-
    {{ .Files.Get "fetch_db_secret.sh" | nindent 4}}
