apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kamu-api-server.fullname" . }}
  labels:
    {{- include "kamu-api-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kamu-api-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with merge
          .Values.podAnnotations
          (ternary (dict "roll-pods" (randAlphaNum 5)) dict (eq .Values.image.pullPolicy "Always"))  }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kamu-api-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kamu-api-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: database-migrations
          image: "{{ .Values.imageMigrations.repository }}:{{ .Values.imageMigrations.tag }}"
          imagePullPolicy: {{ .Values.imageMigrations.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              /scripts/fetch-db-secret.sh {{ .Values.imageMigrations.databaseSecretName }} $AWS_REGION {{ .Values.imageMigrations.databaseProvider }} {{ .Values.imageMigrations.databaseHost }} {{ .Values.imageMigrations.databasePort }} {{ .Values.imageMigrations.databaseName }} &&
              /scripts/run-db-migrations.sh {{ .Values.imageMigrations.migrationsPath }}
          env:
            - name: RUST_BACKTRACE
              value: "1"
            {{- if .Values.app.awsCredentials.enabled }}
            {{- $secretName := include "kamu-api-server.awsCredentialsSecretName" . }}
            - name: AWS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: aws_endpoint
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: aws_region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: aws_secret_access_key
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "/opt/kamu/kamu-api-server"
            - "--config=/opt/kamu/config.yaml"
            - "run"
            - "--address=0.0.0.0"
            - "--http-port=8080"
            - "--flightsql-port=50050"
          env:
            - name: RUST_BACKTRACE
              value: "1"
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.app.awsCredentials.enabled }}
            {{- $secretName := include "kamu-api-server.awsCredentialsSecretName" . }}
            - name: AWS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: aws_endpoint
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: aws_region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: aws_secret_access_key
            {{- end }}
          volumeMounts:
            - name: configs
              subPath: config.yaml
              mountPath: /opt/kamu/config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: flightsql
              containerPort: 50050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: configs
          configMap:
            name: {{ include "kamu-api-server.fullname" . }}-{{ template "kamu-api-server.config.sha" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
