apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kamu-api-server.fullname" . }}
  labels:
    {{- include "kamu-api-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kamu-api-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with merge
          .Values.podAnnotations
          (ternary (dict "roll-pods" (randAlphaNum 5)) dict (eq .Values.image.pullPolicy "Always"))  }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kamu-api-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kamu-api-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "/opt/kamu/kamu-api-server"
            - "--config=/opt/kamu/config.yaml"
            - {{ printf "--repo-url=%s" .Values.app.datasetRepositoryUrl | quote }}
            - "run"
            - "--address=0.0.0.0"
            - "--http-port=80"
            - "--flightsql-port=50050"
          env:
            - name: KAMU_AUTH_GITHUB_CLIENT_ID
              value: {{ .Values.app.authGithubClientId | quote }}
            - name: KAMU_AUTH_GITHUB_CLIENT_SECRET
              value: {{ .Values.app.authGithubClientSecret | quote }}
            - name: KAMU_JWT_SECRET
              value: {{ .Values.app.jwtSecret | quote }}
          volumeMounts:
            - name: configs
              subPath: config.yaml
              mountPath: /opt/kamu/config.yaml
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: flightsql
              containerPort: 50050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: configs
          configMap:
            name: {{ include "kamu-api-server.fullname" . }}-{{ template "kamu-api-server.config.sha" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
