apiVersion: v1
kind: Service
metadata:
  name: {{ include "kamu-oracle-provider.fullname" . }}
  labels:
    {{- include "kamu-oracle-provider.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service }}
  ports:
    - port: {{ .ports.http }}
      name: http
      targetPort: http
      protocol: TCP
      {{- if (and (eq .type "NodePort") .nodePorts.http) }}
      nodePort: {{ .nodePorts.http }}
      {{- end }}
    - port: {{ .ports.https }}
      name: https
      targetPort: http
      protocol: TCP
      {{- if (and (eq .type "NodePort") .nodePorts.https) }}
      nodePort: {{ .nodePorts.https }}
      {{- end }}
    - port: {{ .ports.flightsql }}
      name: flightsql
      targetPort: flightsql
      protocol: TCP
      {{- if (and (eq .type "NodePort") .nodePorts.flightsql) }}
      nodePort: {{ .nodePorts.flightsql }}
      {{- end }}
  {{- end }}
  selector:
    {{- include "kamu-oracle-provider.selectorLabels" . | nindent 4 }}
