apiVersion: v1
kind: Service
metadata:
  name: {{ include "kamu-oracle-provider.fullname" . }}
  labels:
    {{- include "kamu-oracle-provider.labels" . | nindent 4 }}
spec:
  # Headless service, for monitoring only
  clusterIP: None
  type: ClusterIP
  selector:
    {{- include "kamu-oracle-provider.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      name: http
      targetPort: http
      protocol: TCP
