apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kamu-oracle-provider.fullname" . }}
  labels:
    {{- include "kamu-oracle-provider.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kamu-oracle-provider.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 15s
    path: /system/metrics
    port: http
    scheme: http
