{{- if (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-devel.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root_user: {{ .Values.auth.rootUser | b64enc }}
  root_password: {{ include "minio-devel.generateRootPassword" . | b64enc }}
{{- end }}
