apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-devel.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.ports.api }}
      targetPort: api
      {{- if (and (eq .Values.service.type "NodePort") .Values.service.nodePorts.api) }}
      nodePort: {{ .Values.service.nodePorts.api }}
      {{- end }}
    - name: console
      protocol: TCP
      targetPort: console
      port: {{ .Values.service.ports.console }}
      {{- if (and (eq .Values.service.type "NodePort") .Values.service.nodePorts.console) }}
      nodePort: {{ .Values.service.nodePorts.console }}
      {{- end }}
  selector:
    {{- include "minio-devel.selectorLabels" . | nindent 4 }}
